services:
  backend:
    container_name: term-back
    build: /backend
    ports:
      - 8080:8080
  frontend:
    container_name: term-front
    build: /frontend
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000